spring:
  application:
    name: parking-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking-system
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.experiment.parkingsystem.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启了驼峰命名映射的开关
    map-underscore-to-camel-case: true
